In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/synthetic_dataset.csv')

In [3]:
df.head()

  Category   Price    Rating         Stock  Discount
0      NaN  5548.0  1.870322           NaN       0.0
1      NaN  3045.0  4.757798           NaN      38.0
2      NaN  4004.0       NaN      In Stock       0.0
3      NaN  4808.0  1.492085           NaN      33.0
4      NaN  1817.0       NaN  Out of Stock      23.0

In [4]:
df.shape

(4362, 5)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   str
 1   Price     4188 non-null   float64
 2   Rating    2312 non-null   float64
 3   Stock     3010 non-null   str
 4   Discount  3970 non-null   float64
dtypes: float64(3), str(2)
memory usage: 170.5 KB

In [6]:
df['Category'].value_counts(ascending=True)

Category
B    378
A    403
D    408
C    425
Name: count, dtype: int64

In [7]:
df['Stock'].value_counts(ascending=True)

Stock
Out of Stock    1497
In Stock        1513
Name: count, dtype: int64

In [8]:
df.isna().sum()

Category    2748
Price        174
Rating      2050
Stock       1352
Discount     392
dtype: int64

In [9]:
df.describe()

             Price       Rating     Discount
count  4188.000000  2312.000000  3970.000000
mean   5016.970630     3.038293    24.516625
std    2839.984813     1.143074    14.347164
min     102.000000     1.000366     0.000000
25%    2628.250000     2.069490    12.000000
50%    4996.500000     3.082060    25.000000
75%    7418.000000     4.008620    37.000000
max    9999.000000     4.997818    49.000000

In [10]:
num_cols = ['Price', 'Rating', 'Discount']
cat_cols = ['Category', 'Stock']

In [11]:
df[num_cols].corr()

             Price    Rating  Discount
Price     1.000000  0.021099  0.009300
Rating    0.021099  1.000000  0.015028
Discount  0.009300  0.015028  1.000000

## Handling Missing Values

df_dup1: Median Imputation, Mode Imputation, no missing imputer
df_dup2: Median Imputation, Mode Imputation, a missing imputer
df_dup3: Mean Imputation, Mode Imputation, no missing imputer
df_dup4: Mean Imputation, Mode Imputation, a missing imputer
df_dup4: KNN Imputation
df_dup5: Regression Imputation

In [12]:
for col_name in df.columns:
    missing_percent = df[col_name].isnull().mean() * 100
    print(f'Missing Values Percentage in {col_name}: {missing_percent}%')

Missing Values Percentage in Category: 62.99862448418156%
Missing Values Percentage in Price: 3.988995873452544%
Missing Values Percentage in Rating: 46.99679046309033%
Missing Values Percentage in Stock: 30.994956441999083%
Missing Values Percentage in Discount: 8.986703347088492%

Category, Rating and Stock has high percentage of missing values.

In [13]:
df_dup1 = df

In [18]:
for col in df_dup1[num_cols]:
    df_dup1[col].fillna(df_dup1[col].median())

In [19]:
df_dup1[num_cols]

       Price    Rating  Discount
0     5548.0  1.870322       0.0
1     3045.0  4.757798      38.0
2     4004.0       NaN       0.0
3     4808.0  1.492085      33.0
4     1817.0       NaN      23.0
...      ...       ...       ...
4357  4436.0  4.728335      49.0
4358  6236.0       NaN       4.0
4359  3283.0       NaN       9.0
4360  2999.0  4.425995      40.0
4361     NaN  2.184471       0.0

[4362 rows x 3 columns]