In [19]:
import pandas as pd

In [34]:
# Dummy Dataset
df = pd.DataFrame({
    "Education": ["High School", "Bachelor's", "High School", "Master's", "PhD", "High School", "Bachelor's", "Master's", "PhD", "Bachelor's", "High School"]
})

df["Education"].value_counts()

Education
High School    4
Bachelor's     3
Master's       2
PhD            2
Name: count, dtype: int64

### 1. Label Encoding

In [36]:
le_df = df.copy()

In [37]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le_df["Education"] = le.fit_transform(le_df["Education"])

In [38]:
le_df["Education"]

0     1
1     0
2     1
3     2
4     3
5     1
6     0
7     2
8     3
9     0
10    1
Name: Education, dtype: int64

### 2. One Hot Encoding

### Method 1 (Using Pandas)

In [39]:
ohe_df1 = df.copy()

In [42]:
df1_encoded = pd.get_dummies(ohe_df1, columns=["Education"])
df1_encoded

,Education_Bachelor's,Education_High School,Education_Master's,Education_PhD
0,False,True,False,False
1,True,False,False,False
2,False,True,False,False
3,False,False,True,False
4,False,False,False,True
5,False,True,False,False
6,True,False,False,False
7,False,False,True,False
8,False,False,False,True
9,True,False,False,False
10,False,True,False,False

### Method 2 (Using sklearn)

In [43]:
ohe_df2 = df.copy()

In [44]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(ohe_df2[["Education"]])

encoded

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [46]:
encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(["Education"])
)

encoded_df

,Education_Bachelor's,Education_High School,Education_Master's,Education_PhD
0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0
3,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,1.0
5,0.0,1.0,0.0,0.0
6,1.0,0.0,0.0,0.0
7,0.0,0.0,1.0,0.0
8,0.0,0.0,0.0,1.0
9,1.0,0.0,0.0,0.0
10,0.0,1.0,0.0,0.0

### 3. Ordinal Encoding

In [47]:
oe_df = df.copy()

In [50]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(
    categories=[["High School", "Bachelor's", "Master's", "PhD"]]
)

oe_df["Edu_encoded"] = encoder.fit_transform(oe_df[["Education"]])
oe_df

      Education  Edu_encoded
0   High School          0.0
1    Bachelor's          1.0
2   High School          0.0
3      Master's          2.0
4           PhD          3.0
5   High School          0.0
6    Bachelor's          1.0
7      Master's          2.0
8           PhD          3.0
9    Bachelor's          1.0
10  High School          0.0

### 4. Frequency Encoding

In [57]:
fe_df = df.copy()

In [58]:
freq = fe_df["Education"].value_counts(normalize= True)
freq

Education
High School    0.363636
Bachelor's     0.272727
Master's       0.181818
PhD            0.181818
Name: proportion, dtype: float64

In [59]:
fe_df["Edu_freq"] = fe_df["Education"].map(freq)
fe_df

      Education  Edu_freq
0   High School  0.363636
1    Bachelor's  0.272727
2   High School  0.363636
3      Master's  0.181818
4           PhD  0.181818
5   High School  0.363636
6    Bachelor's  0.272727
7      Master's  0.181818
8           PhD  0.181818
9    Bachelor's  0.272727
10  High School  0.363636

### 5. Count Encoding

In [60]:
ce_df = df.copy()

In [63]:
count = ce_df["Education"].value_counts()
count

Education
High School    4
Bachelor's     3
Master's       2
PhD            2
Name: count, dtype: int64

In [64]:
ce_df["Edu_count"] = ce_df["Education"].map(count)
ce_df

      Education  Edu_count
0   High School          4
1    Bachelor's          3
2   High School          4
3      Master's          2
4           PhD          2
5   High School          4
6    Bachelor's          3
7      Master's          2
8           PhD          2
9    Bachelor's          3
10  High School          4